<?php

/**
 * @file
 * Install hooks for this module.
 */

/**
 * Implements hook_install().
 *
 * @see islandora_chemistry_islandora_required_objects()
 */
function islandora_chemistry_install() {
  module_load_include('inc', 'islandora', 'includes/solution_packs');
  islandora_install_solution_pack('islandora_chemistry');
}

/**
 * Implements hook_uninstall().
 */
function islandora_chemistry_uninstall() {
  module_load_include('inc', 'islandora', 'includes/solution_packs');
  islandora_install_solution_pack('islandora_chemistry', 'uninstall');
  $variables = array(
    'islandora_chemistry_python',
    'islandora_chemistry_openbabel',
  );
  array_walk($variables, 'variable_del');
}

/**
 * Implements hook_requirements().
 */
function islandora_chemistry_requirements() {
  if (!libraries_get_path('indigo-python')) {
    $t = get_t();
    $readme_link = l(
      $t('README'),
      drupal_get_path('module', 'islandora_chemistry') . '/README.md'
    );
    return array(
      'indigo-python' => array(
        'title' => $t('Indigo'),
        'description' => $t(
          'Indigo is missing, please consult the !readme for installation instructions.',
          array('!readme' => $readme_link)
        ),
        'severity' => REQUIREMENT_ERROR,
      ),
    );
  }
}

/**
 * Implements hook_schema().
 */
function islandora_chemistry_schema() {
  $schema = array();
  $schema['islandora_chemistry_fingerprints'] = array(
    'description' => 'Table that stores lists of IP ranges.',
    'fields' => array(
      'id' => array(
        'type' => 'serial',
        'unsigned' => TRUE,
        'not null' => TRUE,
      ),
      'inchikey' => array(
        'type' => 'varchar',
        'length' => 50,
        'not null' => TRUE,
      ),
    ),
    'primary key' => array('id'),
    'indexes' => array('inchikey' => array('inchikey')),
  );
  for ($i = 0; $i <= 116; $i++) {
    $schema['islandora_chemistry_fingerprints']['fields']["fp$i"] = array(
      'type' => 'int',
      'size' => 'big',
      'length' => 64,
      'unsigned' => TRUE,
      'not null' => TRUE,
      'default' => 0,
    );
  }
  return $schema;
}
