<?php

/**
 * @file
 * Hooks and callbacks for this module.
 */

/**
 * Implements hook_theme().
 */
function islandora_chemistry_theme($existing, $type, $theme, $path) {
  return array(
    'islandora_chemistry' => array(
      'template' => 'theme/islandora-chemistry',
      'pattern' => 'islandora_chemistry__',
      'variables' => array('islandora_object' => NULL),
    ),
  );
}

/**
 * Implements hook_islandora_required_objects().
 */
function islandora_chemistry_islandora_required_objects(IslandoraTuque $connection) {
  $module_path = drupal_get_path('module', 'islandora_chemistry');
  // Chemistry Content Model.
  $chemistry_model = $connection->repository->constructObject('islandora:sp_chem_CM');
  $chemistry_model->owner = 'fedoraAdmin';
  $chemistry_model->label = 'Islandora Chemistry Content Model';
  $chemistry_model->models = 'fedora-system:ContentModel-3.0';
  // DS-COMPOSITE-MODEL Datastream.
  $datastream = $chemistry_model->constructDatastream('DS-COMPOSITE-MODEL', 'X');
  $datastream->label = 'DS-COMPOSITE-MODEL';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_chemistry_ds_composite_model.xml", FALSE);
  $chemistry_model->ingestDatastream($datastream);
  // Chemistry Collection.
  $chemistry_collection = $connection->repository->constructObject('islandora:chemistry_collection');
  $chemistry_collection->owner = 'fedoraAdmin';
  $chemistry_collection->label = 'Chemistry Collection';
  $chemistry_collection->models = 'islandora:collectionCModel';
  $chemistry_collection->relationships->add(FEDORA_RELS_EXT_URI, 'isMemberOfCollection', 'islandora:root');
  // Collection Policy Datastream.
  $datastream = $chemistry_collection->constructDatastream('COLLECTION_POLICY', 'X');
  $datastream->label = 'Collection policy';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_chemistry_collection_policy.xml", FALSE);
  $chemistry_collection->ingestDatastream($datastream);
  // TN Datastream.
  $datastream = $chemistry_collection->constructDatastream('TN', 'M');
  $datastream->label = 'Thumbnail';
  $datastream->mimetype = 'image/png';
  $datastream->setContentFromFile("$module_path/images/folder.png", FALSE);
  $chemistry_collection->ingestDatastream($datastream);
  return array(
    'islandora_chemistry' => array(
      'title' => 'Islandora Chemistry',
      'objects' => array(
        $chemistry_model,
        $chemistry_collection,
      ),
    ),
  );
}

/**
 * Implements hook_islandora_xml_form_builder_forms().
 */
function islandora_chemistry_islandora_xml_form_builder_forms() {
  $module_path = drupal_get_path('module', 'islandora_chemistry');
  return array(
    'Chemistry MODS form' => array(
      'form_file' => "$module_path/xml/islandora_chemistry_form_mods.xml",
    ),
  );
}

/**
 * Implements hook_islandora_xml_form_builder_form_associations().
 */
function islandora_chemistry_islandora_xml_form_builder_form_associations() {
  return array(
    'islandora_chemistry_mods_form' => array(
      'content_model' => 'islandora:sp_chem_CM',
      'form_name' => 'Chemistry MODS form',
      'dsid' => 'MODS',
      'title_field' => array('titleInfo', 'title'),
      'transform' => 'mods_to_dc.xsl',
      'template' => FALSE,
    ),
  );
}

/**
 * Implements hook_islandora_ingest_steps().
 */
function islandora_chemistry_islandora_sp_chem_CM_islandora_ingest_steps() {
  return array(
    'chemistry_upload' => array(
      'weight' => 10,
      'type' => 'form',
      'form_id' => 'islandora_chemistry_upload_form',
      'module' => 'islandora_chemistry',
      'file' => 'includes/chemistry_upload.form.inc',
    ),
  );
}

/**
 * Implements hook_CMODEL_PID_islandora_view_object().
 */
function islandora_chemistry_islandora_sp_chem_CM_islandora_view_object($object, $page_number, $page_size) {
  return array(
    'islandora_chemistry' => array(
      '#type' => 'markup',
      '#theme' => 'islandora_chemistry',
      '#islandora_object' => $object,
    ),
  );
}

/**
 * Implements hook_menu().
 */
function islandora_chemistry_menu() {
  $items = array();

  $items['islandora/object/%islandora_object/chemistry/3d-view'] = array(
    'title' => '3D View',
    'page callback' => 'islandora_chemistry_3d_view',
    'page arguments' => array(2),
    'access callback' => 'islandora_chemistry_3d_view_access',
    'access arguments' => array(2),
    'type' => MENU_LOCAL_TASK,
    'file' => 'includes/3d-view.tab.inc',
  );

  return $items;
}

/**
 * Access callback for 3D molecule view.
 */
function islandora_chemistry_3d_view_access(AbstractObject $object) {
  return isset($object['MOL']) && in_array('islandora:sp_chem_CM', $object->models) &&  islandora_datastream_access(ISLANDORA_VIEW_OBJECTS, $object['MOL']);
}
