<?php

/**
 * @file
 * Hooks and callbacks for this module.
 */

/**
 * Implements hook_theme().
 */
function islandora_chemistry_theme($existing, $type, $theme, $path) {
  return array(
    'islandora_chemistry' => array(
      'template' => 'theme/islandora-chemistry',
      'pattern' => 'islandora_chemistry__',
      'variables' => array('islandora_object' => NULL),
    ),
  );
}

/**
 * Implements hook_islandora_required_objects().
 */
function islandora_chemistry_islandora_required_objects(IslandoraTuque $connection) {
  $module_path = drupal_get_path('module', 'islandora_chemistry');
  // Chemistry Content Model.
  $chemistry_model = $connection->repository->constructObject('islandora:sp_chem_CM');
  $chemistry_model->owner = 'fedoraAdmin';
  $chemistry_model->label = 'Islandora Chemistry Content Model';
  $chemistry_model->models = 'fedora-system:ContentModel-3.0';
  // DS-COMPOSITE-MODEL Datastream.
  $datastream = $chemistry_model->constructDatastream('DS-COMPOSITE-MODEL', 'X');
  $datastream->label = 'DS-COMPOSITE-MODEL';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_chemistry_ds_composite_model.xml", FALSE);
  $chemistry_model->ingestDatastream($datastream);
  // Chemistry Collection.
  $chemistry_collection = $connection->repository->constructObject('islandora:chemistry_collection');
  $chemistry_collection->owner = 'fedoraAdmin';
  $chemistry_collection->label = 'Chemistry Collection';
  $chemistry_collection->models = 'islandora:collectionCModel';
  $chemistry_collection->relationships->add(FEDORA_RELS_EXT_URI, 'isMemberOfCollection', 'islandora:root');
  // Collection Policy Datastream.
  $datastream = $chemistry_collection->constructDatastream('COLLECTION_POLICY', 'X');
  $datastream->label = 'Collection policy';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_chemistry_collection_policy.xml", FALSE);
  $chemistry_collection->ingestDatastream($datastream);
  // TN Datastream.
  $datastream = $chemistry_collection->constructDatastream('TN', 'M');
  $datastream->label = 'Thumbnail';
  $datastream->mimetype = 'image/png';
  $datastream->setContentFromFile("$module_path/images/folder.png", FALSE);
  $chemistry_collection->ingestDatastream($datastream);
  return array(
    'islandora_chemistry' => array(
      'title' => 'Islandora Chemistry',
      'objects' => array(
        $chemistry_model,
        $chemistry_collection,
      ),
    ),
  );
}

/**
 * Implements hook_islandora_xml_form_builder_forms().
 */
function islandora_chemistry_islandora_xml_form_builder_forms() {
  $module_path = drupal_get_path('module', 'islandora_chemistry');
  return array(
    'Chemistry MODS form' => array(
      'form_file' => "$module_path/xml/islandora_chemistry_form_mods.xml",
    ),
  );
}

/**
 * Implements hook_islandora_xml_form_builder_form_associations().
 */
function islandora_chemistry_islandora_xml_form_builder_form_associations() {
  return array(
    'islandora_chemistry_mods_form' => array(
      'content_model' => 'islandora:sp_chem_CM',
      'form_name' => 'Chemistry MODS form',
      'dsid' => 'MODS',
      'title_field' => array('titleInfo', 'title'),
      'transform' => 'mods_to_dc.xsl',
      'template' => FALSE,
    ),
  );
}

/**
 * Implements hook_islandora_ingest_steps().
 */
function islandora_chemistry_islandora_sp_chem_CM_islandora_ingest_steps() {
  return array(
    'chemistry_upload' => array(
      'weight' => 10,
      'type' => 'form',
      'form_id' => 'islandora_chemistry_upload_form',
      'module' => 'islandora_chemistry',
      'file' => 'includes/chemistry_upload.form.inc',
    ),
  );
}

/**
 * Implements hook_CMODEL_PID_islandora_view_object().
 */
function islandora_chemistry_islandora_sp_chem_CM_islandora_view_object($object, $page_number, $page_size) {
  return theme('islandora_chemistry', array('islandora_object' => $object));
}

/**
 * Implements hook_block_info().
 */
function islandora_chemistry_block_info() {
  return array(
    'islandora_chemistry_upload' => array(
      'info' => t('Islandora Chemistry Upload A File'),
      'cache' => DRUPAL_NO_CACHE,
    ),
    'structure_search' => array(
      'info' => t('Islandora Chemistry Structure Search'),
      'cache' => DRUPAL_NO_CACHE,
    ),
  );
}

/**
 * Implements hook_block_view().
 */
function islandora_chemistry_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'islandora_chemistry_upload':
      if (user_access(ISLANDORA_INGEST)) {
        module_load_include('inc', 'islandora_chemistry', 'includes/blocks');
        $block['subject'] = t('Upload Structures');
        $block['content'] = drupal_get_form('islandora_chemistry_upload_file_form');
      }
      break;

    case 'structure_search':
      if (user_access('search islandora solr')) {
        module_load_include('inc', 'islandora_chemistry', 'includes/blocks');
        $block['subject'] = t('Structure Search');
        $block['content'] = drupal_get_form('islandora_chemistry_structure_search_form');
        dsm($block, 'block');
      }
      break;
  }
  return $block;
}

/**
 * Implements hook_menu().
 */
function islandora_chemistry_menu() {
  return array(
    'admin/islandora/solution_pack_config/chemistry' => array(
      'title' => 'Chemistry Solution Pack',
      'description' => 'Configure Islandora Chemistry solution pack.',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('islandora_chemistry_admin_settings_form'),
      'access arguments' => array('administer site configuration'),
      'file' => 'includes/admin.form.inc',
      'type' => MENU_NORMAL_ITEM,
    ),
  );
}

/**
 * Implements hook_CMODEL_PID_islandora_derivative().
 */
function islandora_chemistry_islandora_sp_chem_cm_islandora_derivative() {
  $derivatives = array();

  $module_path = drupal_get_path('module', 'islandora_chemistry');

  $derivatives['islandora_chemistry_mol'] = array(
    'source_dsid' => 'OBJ',
    'destination_dsid' => 'MOL',
    'function' => array(
      'islandora_chemistry_derive_mol',
    ),
    'file' => "$module_path/includes/derivatives.inc",
  );
  $derivatives['islandora_chemistry_medium'] = array(
    'source_dsid' => 'OBJ',
    'destination_dsid' => 'MEDIUM',
    'function' => array(
      'islandora_chemistry_derive_medium',
    ),
    'file' => "$module_path/includes/derivatives.inc",
  );
  $derivatives['islandora_chemistry_tn'] = array(
    'source_dsid' => 'OBJ',
    'destination_dsid' => 'TN',
    'function' => array(
      'islandora_chemistry_derive_tn',
    ),
    'file' => "$module_path/includes/derivatives.inc",
  );

  return $derivatives;
}

/**
 * Implements hook_file_mimetype_mapping_alter().
 *
 * Override mapping for chemical MIME-types, as some are mapped incorrectly,
 * such as ".gam" being mapped to "chemical/x-gamess-input", while its proper
 * mapping would be "chemical/x-gamess-output".
 */
function islandora_chemistry_file_mimetype_mapping_alter(&$mapping) {
  $chem_filter = function ($mimetype) {
    return strpos($mimetype, 'chemical/') === 0;
  };

  $mime_detect = new MimeDetect();
  $types = $mime_detect->getMimeTypes();
  $filtered_types = array_filter($types, $chem_filter);

  $intersect = array_intersect_key($types, $mapping['extensions']);
  foreach ($intersect as $ext => $mime) {
    $keys = array_keys($mapping['mimetypes'], $mime);
    if (empty($keys)) {
      $mapping['mimetypes'][] = $mime;
      $keys = array_keys($mapping['mimetypes'], $mime);
    }
    $mapping['extensions'][$ext] = reset($keys);
  }
}
