<?php

/**
 * @file
 * Install hooks for this module.
 */

/**
 * Implements hook_install().
 *
 * @see islandora_chemistry_islandora_required_objects()
 */
function islandora_chemistry_install() {
  module_load_include('inc', 'islandora', 'includes/solution_packs');
  islandora_install_solution_pack('islandora_chemistry');
}

/**
 * Implements hook_uninstall().
 */
function islandora_chemistry_uninstall() {
  module_load_include('inc', 'islandora', 'includes/solution_packs');
  islandora_install_solution_pack('islandora_chemistry', 'uninstall');
}
